// Code generated by Kitex v0.12.0. DO NOT EDIT.

package cartservice

import (
	"context"
	cart "eshop_cart/kitex_gen/eshop/cart"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddItem(ctx context.Context, req *cart.AddItemRequest, callOptions ...callopt.Option) (r *cart.BaseResponse, err error)
	GetList(ctx context.Context, req *cart.PageRequest, callOptions ...callopt.Option) (r *cart.PageResponse, err error)
	UpdateItem(ctx context.Context, req *cart.UpdateRequest, callOptions ...callopt.Option) (r *cart.UpdateResponse, err error)
	DeleteItem(ctx context.Context, req *cart.DeleteRequest, callOptions ...callopt.Option) (r *cart.BaseResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCartServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCartServiceClient struct {
	*kClient
}

func (p *kCartServiceClient) AddItem(ctx context.Context, req *cart.AddItemRequest, callOptions ...callopt.Option) (r *cart.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddItem(ctx, req)
}

func (p *kCartServiceClient) GetList(ctx context.Context, req *cart.PageRequest, callOptions ...callopt.Option) (r *cart.PageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetList(ctx, req)
}

func (p *kCartServiceClient) UpdateItem(ctx context.Context, req *cart.UpdateRequest, callOptions ...callopt.Option) (r *cart.UpdateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateItem(ctx, req)
}

func (p *kCartServiceClient) DeleteItem(ctx context.Context, req *cart.DeleteRequest, callOptions ...callopt.Option) (r *cart.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteItem(ctx, req)
}
